name: PKUAutoSubmit

on:
  schedule:
    - cron: '* */4 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7

      - name: 'Install requirements'
        run: pip install selenium

      - name: 'decryping'
        run: |
          openssl enc -aes-256-cbc -md sha512 -pbkdf2 -d -in player.enc -out player.ini -pass pass:${{secrets.key}}

      - name: 'Working'
        run: python main.py
        
      - name: 'Delete cryp'
        run: rm player.ini

      - name: 'Refresh'
        run: |
          git config --global user.email "siumabon123@gmail.com"
          git config --global user.name "See.Loooo"
          git add -A
          git diff-index --quiet HEAD || git commit -m "refresh Date"
          git push origin master
